# Generated by Django 3.0.4 on 2020-04-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('odometro', models.BigIntegerField(default=0, verbose_name='Odometro')),
                ('monto', models.FloatField(default=0, verbose_name='Monto')),
                ('precio_litro', models.FloatField(default=0, verbose_name='Precio X Litro')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha De Ingreso')),
                ('boleta', models.BigIntegerField(default=0, verbose_name='Numero Boleta')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Consumo',
                'verbose_name_plural': 'Consumos',
                'ordering': ['id'],
            },
        ),
    ]
